### ISSUE TITLE
Why is this one much smaller?

### ISSUE THREAD

**Issue by reworkhow** [cbkmephisto/dockerfile-jwas-mini#1]

**Comment by cbkmephisto** [comment]
This one is built based on an `ubuntu` image, installing only the necessary packages and libraries. I haven't tested it throughly yet but I think it will be working the same as the official one.

**Comment by reworkhow** [comment]
Can you double check it? If it works, I will ask users to use this one.

**Comment by cbkmephisto** [comment]
I tried all notebooks in [JWAS notebooks](https://github.com/reworkhow/JWAS-Docker/tree/master/JWAS_notebooks), but a lot of errors showed up - I think they're caused by inconsistence of different versions, i.e. these notebooks were written for JWAS older versions and will not work on the current version.

Also I've add "Plots" package into this image, maybe "Gadfly" too, but we don't have a specified list of packages to install yet.

**Comment by reworkhow** [comment]
I has a look at your docker file. Looks like the major difference is that you built it from ubuntu.

**Comment by cbkmephisto** [comment]
You could use it to build the official image; I just need this copy for potential future use...

**Comment by reworkhow** [comment]
I have new notebooks in the big JWAS docker file now. Everything works nicely.

**Comment by reworkhow** [comment]
> Then, open the url in an internect browser (IE, Firefox, Chrome, Safari, etc), change the IP address from 0.0.0.0:
> to 127.0.0.1 (if running docker and visiting from your local machine), or

Why do I need to do this on my local machine?

**Comment by cbkmephisto** [comment]
You're right - I don't know 0.0.0.0 works on local machine. Descriptions will be changed.

**Comment by reworkhow** [comment]
I tried to merge your on to the official one. https://github.com/reworkhow/JWAS-Docker
Is this okay with you?

**Comment by cbkmephisto** [comment]
No problem - it'd be easier to maintain.

**Comment by reworkhow** [comment]
Good! You may want to modify the readme for the url thing.
